name: hyppe
description: Hyppe Teknologi Indonesia.
homepage: https://www.hyppe.id

publish_to: "none"

version: 1.2.0+91 #22-03-2023
 

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase and google services
  firebase_core: ^2.4.1 # Enabling connecting to multiple Firebase apps.
  firebase_dynamic_links: ^5.0.11 # For using dynamic link feature
  firebase_messaging: ^14.2.1 # A Flutter plugin to use the Firebase Cloud Messaging (FCM) API
  google_sign_in: ^5.2.4 # A secure authentication system for signing in with a Google account on Android and iOS.
  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.10

  cached_network_image: ^3.2.3 # Untuk keperluan cache image
  # camera: ^0.9.4+21 # Accessing camera feature
  camera: ^0.10.0 # Accessing camera feature
  carousel_slider: ^4.0.0 # Untuk kebutuhan Carousel Slider
  cupertino_icons: ^1.0.4 # The following adds the Cupertino Icons font to your application, Use with the CupertinoIcons class for iOS style icons.
  dio: ^5.0.1 # Untuk kebutuhan [HTTP Request]
  file_picker: ^4.4.0 # Use a native file explorer to pick single or multiple absolute file paths, with extension filtering support
  flutter_local_notifications: ^9.9.1 # Untuk kebutuhan push notification
  flutter_svg: ^1.0.3 # Untuk kebutuhan rendering svg file
  flutter_video_info: ^1.2.0 # Get basic metadata information of a video file.
  http_parser: ^4.0.0 # A platform-independent package for parsing and serializing HTTP formats.
  intl: ^0.17.0 # Untuk kebutuhan format date and time
  lottie: ^1.2.1 # load image
  path_provider: ^2.0.8 # Untuk kebutuhan get path directory di device
  permission_handler: ^10.0.0 # Untuk kebutuhan handling permission
  provider: ^6.0.2 # Untuk kebutuhan state management
  share_plus: ^4.0.10 # Untuk kebutuhan sharing content to another apps
  shared_preferences: ^2.0.12 # Untuk kebutuhan penyimpanan memory internal
  shimmer: ^2.0.0 # A package provides an easy way to add shimmer effect in Flutter project
  tuple: ^2.0.0 # Tuple data structure
  visibility_detector: ^0.3.3 # A widget that detects the visibility of its child and notifies a callback
  video_thumbnail: ^0.5.3
  device_info_plus: ^3.2.1 # providing detailed information about the device (make, model, etc.)
  collection: ^1.16.0 # Collections and utilities functions and classes related to collections.
  computer: ^3.2.0 # Easy to use pool of concurrent workers with compute() like API.
  package_info_plus: ^1.3.0 # For querying information about the application package
  flutter_inappwebview: ^5.7.2+3 # To add an inline webview, to use an headless webview, and to open an in-app browser window
  pin_code_fields: ^7.4.0 # Help to generate pin code fields.
  flutter_markdown: ^0.6.8 # A markdown viewer for flutter
  native_device_orientation: ^1.0.0 # A plugin project that allows for getting the native device orientation.
  socket_io_client: ^2.0.0-beta.4-nullsafety.0 # Dartlang port of socket.io-client for web, flutter, dartvm to use.
  image_picker: ^0.8.4+9 # Picking images from the image library, and taking new pictures with the camera.
  # flutter_facebook_auth: ^4.3.0
  # twitter_login: ^4.2.2
  location: ^4.4.0
  url_launcher: ^6.1.10
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.0 
  uuid: ^3.0.6
  light_compressor: ^1.2.2
  deepar_flutter: ^0.0.5
  flutter_html: ^3.0.0-alpha.3
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
  marquee: ^2.2.3
  ffmpeg_kit_flutter: ^5.1.0
  audioplayers: ^2.0.0
  image_cropper: ^3.0.1
  move_to_background: ^1.0.2
  sqflite: ^2.2.3
  # secure_application: ^3.8.0
  screen_protector: ^1.2.0  
  wakelock: ^0.6.2
  exif: ^3.1.2
  flutter_image_compress: ^1.1.3
  flutter_aliplayer: ^5.4.9
  pull_to_refresh: ^2.0.0
  dio_http_formatter: ^3.0.0-preview.1
  webview_flutter: ^4.0.7
#  preload_page_view: ^0.1.6



  dynamic_widget: # Dynamic widget builder
    git:
      url: https://github.com/dengyin2000/dynamic_widget.git
      ref: 93fb01345de507f0ed523c3ec1f8bbc12dbf79c0

  better_player: # Better player
    path: ../hyppe-better-player

  story_view: # Story viewer
    path: packages/story_view
  
  qr_flutter: ^4.0.0
  pattern_formatter: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  #flutter_masked_text: ^0.8.0 #currency format for input text

  # google_ml_kit: ^0.12.0 # Text recognition
  google_mlkit_text_recognition: ^0.5.0

#  curl_logger_dio_interceptor: ^0.0.3

  # uuid: ^3.0.4 # UUID Generator and Parser for all Dart platforms
  # stomp_dart_client: ^0.4.3 # For easy messaging interoperability

 
# dependency_overrides:
#  firebase_core_platform_interface: 4.5.1
#   camera: <=0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
#  hive_generator: ^1.1.3
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/eula.html
    - assets/bca-internet-banking.html
    - assets/fonts/
    - assets/json/
    - assets/png/
    - assets/vector/
    - assets/dummy_md/
    - assets/effect/
    - assets/effect/BurningEffect/
    - assets/effect/DevilNeonHorns/
    - assets/effect/ElephantTrunk/
    - assets/effect/EmotionMeter/
    - assets/effect/EmotionsExaggerator/
    - assets/effect/FireEffect/
    - assets/effect/FlowerFace/
    - assets/effect/Hope/
    - assets/effect/Humanoid/
    - assets/effect/MakeupLookw_Slipt/
    - assets/effect/PingPongMinigame/
    - assets/effect/Snail/
    - assets/effect/Stallone/
    - assets/effect/VendettaMask/
    - assets/effect/VikingHelmetPBR/
    - assets/effect/BabyChewbacca/
    - assets/effect/BigGlasses/
    - assets/effect/Chief/
    - assets/effect/CrossedEyes/
    - assets/effect/FreeBeauty/
    - assets/effect/Jokester/
    - assets/effect/LizardSkin/
    - assets/effect/NeonWires/
    - assets/effect/Peter/
    - assets/effect/PopFace/
    - assets/effect/Samurai/
 
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf
