name: hyppe
description: Hyppe Teknologi Indonesia.
homepage: https://www.hyppe.id

publish_to: "none"

version: 1.6.0+152 #26-06-2023

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase and google services
  firebase_core: ^2.4.1 # Enabling connecting to multiple Firebase apps.
  firebase_dynamic_links: ^5.0.11 # For using dynamic link feature
  firebase_messaging: ^14.2.1 # A Flutter plugin to use the Firebase Cloud Messaging (FCM) API
  google_sign_in: ^5.2.4 # A secure authentication system for signing in with a Google account on Android and iOS.
  firebase_auth: 4.2.5
  firebase_auth_platform_interface: 6.15.3
  firebase_crashlytics: ^3.0.10

  firebase_analytics: ^10.5.0

  cached_network_image: ^3.2.3 # Untuk keperluan cache image
  # camera: ^0.9.4+21 # Accessing camera feature
  camera: ^0.10.0 # Accessing camera feature
  carousel_slider: ^4.2.1 # Untuk kebutuhan Carousel Slider
  cupertino_icons: ^1.0.4 # The following adds the Cupertino Icons font to your application, Use with the CupertinoIcons class for iOS style icons.
  dio: ^5.0.1 # Untuk kebutuhan [HTTP Request]
  # file_picker: ^4.4.0 # Use a native file explorer to pick single or multiple absolute file paths, with extension filtering support
  flutter_local_notifications: ^9.9.1 # Untuk kebutuhan push notification
  flutter_svg: ^1.0.3 # Untuk kebutuhan rendering svg file
  flutter_video_info: ^1.2.0 # Get basic metadata information of a video file.
  http_parser: ^4.0.0 # A platform-independent package for parsing and serializing HTTP formats.
  intl: ^0.17.0 # Untuk kebutuhan format date and time
  lottie: ^1.2.1 # load image
  path_provider: ^2.0.8 # Untuk kebutuhan get path directory di device
  permission_handler: ^10.0.0 # Untuk kebutuhan handling permission
  provider: ^6.0.2 # Untuk kebutuhan state management
  share_plus: ^4.0.10 # Untuk kebutuhan sharing content to another apps
  shared_preferences: ^2.0.12 # Untuk kebutuhan penyimpanan memory internal
  shimmer: ^2.0.0 # A package provides an easy way to add shimmer effect in Flutter project
  tuple: ^2.0.0 # Tuple data structure
  visibility_detector: ^0.3.3 # A widget that detects the visibility of its child and notifies a callback
  video_thumbnail: ^0.5.3
  device_info_plus: ^9.1.0 # providing detailed information about the device (make, model, etc.)
  collection: ^1.16.0 # Collections and utilities functions and classes related to collections.
  computer: ^3.2.0 # Easy to use pool of concurrent workers with compute() like API.
  package_info_plus: ^4.2.0 # For querying information about the application package
  flutter_inappwebview: ^5.7.2+3 # To add an inline webview, to use an headless webview, and to open an in-app browser window
  pin_code_fields: ^7.4.0 # Help to generate pin code fields.
  flutter_markdown: ^0.6.8 # A markdown viewer for flutter
  native_device_orientation: ^1.0.0 # A plugin project that allows for getting the native device orientation.
  socket_io_client: ^2.0.0-beta.4-nullsafety.0 # Dartlang port of socket.io-client for web, flutter, dartvm to use.
  image_picker: ^0.8.4+9 # Picking images from the image library, and taking new pictures with the camera.
  # flutter_facebook_auth: ^4.3.0
  # twitter_login: ^4.2.2
  location: ^5.0.3
  url_launcher: ^6.1.10
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.0
  uuid: ^3.0.6
  light_compressor: ^1.2.2
  flutter_html: ^3.0.0-alpha.3
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
  marquee: ^2.2.3
  ffmpeg_kit_flutter: ^6.0.3
  audioplayers: ^2.0.0
  image_cropper: ^4.0.1
  move_to_background: ^1.0.2
  sqflite: ^2.2.3
  # secure_application: ^3.8.0
  screen_protector: ^1.3.2
  wakelock_plus: ^1.1.3
  exif: ^3.1.2
  flutter_image_compress: ^1.1.3
  flutter_aliplayer: 5.4.10
  pull_to_refresh: ^2.0.0
  dio_http_formatter: ^3.0.0-preview.1
  webview_flutter: ^4.0.7
#  preload_page_view: ^0.1.6
  photo_view: ^0.14.0
  pinch_zoom: ^1.0.0
  full_screen_image: ^2.0.0
  zoom_pinch_overlay: ^1.4.1+3
  scrollable_positioned_list: ^0.3.8
  measured_size: ^1.0.0
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  gif_view: ^0.3.1
  gif: ^2.2.0
  auto_size_text: ^3.0.0
  image: ^4.1.3
  fhoto_editor: ^0.0.2
  colorfilter_generator: ^0.0.8
  fraction: ^4.1.4
  themed: ^4.0.0

  flutter_livepush_plugin: ^2.1.0+1

  heif_converter: ^1.0.0

  dynamic_widget: # Dynamic widget builder
    git:
      url: https://github.com/dengyin2000/dynamic_widget.git
      ref: 93fb01345de507f0ed523c3ec1f8bbc12dbf79c0


  video_editor:
    path: packages/video_editor

  video_player:
    path: packages/video_player

  showcaseview: # Story viewer
    path: packages/showcaseview

  # deepar_flutter: ^0.0.5
  deepar_flutter: # Flutter DeepAR
    path: packages/deepar_flutter

  # matrix_gesture_detector: ^0.2.0-nullsafety.1
  matrix_gesture_detector:
    path: packages/matrix_gesture_detector
  

  # matrix_gesture_detector: ^0.2.0-nullsafety.1
  file_picker:
    path: packages/file_picker-4.6.1
  

  qr_flutter: ^4.1.0
  pattern_formatter: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  #flutter_masked_text: ^0.8.0 #currency format for input text

  # google_ml_kit: ^0.12.0 # Text recognition
  google_mlkit_text_recognition: ^0.5.0
  
  flutter_sharing_intent: ^1.1.0
  receive_sharing_intent: ^1.4.5
  receive_intent: ^0.2.4
  # snappy_list_view: ^0.1.0
  # scroll_snap_list: ^0.9.1
  fluttertoast: ^8.2.4

  

#  curl_logger_dio_interceptor: ^0.0.3

  # uuid: ^3.0.4 # UUID Generator and Parser for all Dart platforms
  # stomp_dart_client: ^0.4.3 # For easy messaging interoperability

 
# dependency_overrides:
#  firebase_core_platform_interface: 4.5.1
#   camera: <=0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
#  hive_generator: ^1.1.3
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/eula.html
    - assets/bca-internet-banking.html
    - assets/fonts/
    - assets/json/
    - assets/png/
    - assets/vector/
    - assets/dummy_md/
 
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf