name: flutter_verification_code
homepage: https://github.com/awaik/flutter_verification_code.git
description: A Flutter package that help you create a verification input.
version: 1.1.7

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4