// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdDXmkb4LyPu7s2LfIuUW5srrQ6vB_Yns',
    appId: '1:590985523606:android:8131427f19f46a74a92db7',
    messagingSenderId: '590985523606',
    projectId: 'hyppeapp-297310',
    databaseURL: 'https://hyppeapp-297310.firebaseio.com',
    storageBucket: 'hyppeapp-297310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2yRgyOVZH0O34kIWwTwkw5AqZqqy-Rg',
    appId: '1:590985523606:ios:049b5ff1f1907858a92db7',
    messagingSenderId: '590985523606',
    projectId: 'hyppeapp-297310',
    databaseURL: 'https://hyppeapp-297310.firebaseio.com',
    storageBucket: 'hyppeapp-297310.appspot.com',
    androidClientId: '590985523606-7flb010dksrq94km52g4atu14vh8qu9u.apps.googleusercontent.com',
    iosClientId: '590985523606-cp9mhs1a7g18i8bapo8cuujjnet4f0pv.apps.googleusercontent.com',
    iosBundleId: 'com.hyppe.hyppeapp',
  );
}
